export async function query() {
  const db = [
    {
      AcceptedPaymentTypes: [
        {
          SiteManagementItem: {
            Title: "All Major Credit Cards",
            HideInSearch: false,
            SortOrder: 1,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Cash Accepted",
            HideInSearch: false,
            SortOrder: 2,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "ComCheck",
            HideInSearch: false,
            SortOrder: 3,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "EBT/SNAP Accepted",
            HideInSearch: false,
            SortOrder: 4,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Fleet One",
            HideInSearch: false,
            SortOrder: 5,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "EFS",
            HideInSearch: false,
            SortOrder: 6,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "FlyingK Express",
            HideInSearch: false,
            SortOrder: 7,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "MultiService",
            HideInSearch: false,
            SortOrder: 8,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "T-Chek",
            HideInSearch: false,
            SortOrder: 9,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "TCH",
            HideInSearch: false,
            SortOrder: 10,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "QuikQ FPS",
            HideInSearch: false,
            SortOrder: 11,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
      ],
      AdditionalAmenities: [
        {
          SiteManagementItem: {
            Title: "24-Hour Road Service",
            HideInSearch: false,
            SortOrder: 1,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Open 24-Hours",
            HideInSearch: false,
            SortOrder: 2,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Additives Available",
            HideInSearch: false,
            SortOrder: 3,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Calling Cards",
            HideInSearch: false,
            SortOrder: 4,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Check Cashing",
            HideInSearch: false,
            SortOrder: 5,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Copy & Fax Service",
            HideInSearch: false,
            SortOrder: 6,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "DEF Retail",
            HideInSearch: false,
            SortOrder: 7,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Overnight Parking",
            HideInSearch: false,
            SortOrder: 8,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Permit Fax",
            HideInSearch: false,
            SortOrder: 9,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Loyalty Program",
            HideInSearch: false,
            SortOrder: 10,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "TripPak Express",
            HideInSearch: false,
            SortOrder: 11,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
      ],
      Addresses: [
        {
          Address1: "300 Arby Dr.",
          Address2: "",
          AddressId: 1209,
          AddressTypeId: 1,
          City: "Clanton",
          Comments: "",
          County: null,
          Name: "Clanton - 368",
          SpecialInstructions: "",
          State: "AL",
          Zip: "35045",
        },
      ],
      ContactMethods: [
        {
          Type: {
            Id: 4,
            Name: "Rollover Phone",
            IsActive: true,
          },
          Id: 2196,
          ContactMethodTypeId: 4,
          Data: "(205) 755-8352",
        },
        {
          Type: {
            Id: 1,
            Name: "Main Phone",
            IsActive: true,
          },
          Id: 2195,
          ContactMethodTypeId: 1,
          Data: "(205) 755-8104",
        },
        {
          Type: {
            Id: 5,
            Name: "Fax",
            IsActive: true,
          },
          Id: 2197,
          ContactMethodTypeId: 5,
          Data: "(205) 755-8694",
        },
        {
          Type: {
            Id: 2,
            Name: "Main Email",
            IsActive: true,
          },
          Id: 970,
          ContactMethodTypeId: 2,
          Data: "Store368@example.com",
        },
      ],
      CustomFields: [
        {
          CustomField: {
            Id: 411,
            Label: "Private Showers",
            Name: "PrivateShowers",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/shower.ashx",
            DisplayName: "Private Showers",
            SortOrder: 1,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 383,
            Label: "CAT Scales",
            Name: "CATScales",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/cat.ashx",
            DisplayName: "CAT Scales",
            SortOrder: 2,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 391,
            Label: "Wireless Internet",
            Name: "WirelessInternet",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/internet.ashx",
            DisplayName: "WiFi",
            SortOrder: 3,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 515,
            Label: "ATM",
            Name: "ATM",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/atm.ashx",
            DisplayName: "ATM",
            SortOrder: 4,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 13,
            Label: "Transflo",
            Name: "Transflo",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/transFlo.ashx",
            DisplayName: "Transflo",
            SortOrder: 5,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 371,
            Label: "Overnight Parking",
            Name: "OvernightParking",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/nightParking.ashx",
            DisplayName: "Truck Parking",
            SortOrder: 6,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 359,
            Label: "RV Dump",
            Name: "RVDump",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/rvDump.ashx",
            DisplayName: "RV Dump Service",
            SortOrder: 7,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 407,
            Label: "DEF Bulk Dispensers",
            Name: "DEFBulkDispensers",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/bulkDef.ashx",
            DisplayName: "Bulk DEF",
            SortOrder: 8,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 351,
            Label: "RF Service",
            Name: "RFService",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/rf.ashx",
            DisplayName: "RFID Pump Start",
            SortOrder: 9,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 387,
            Label: "National Tire Account",
            Name: "NationalTireAccount",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/tireCare.ashx",
            DisplayName: "Truck Tire Care",
            SortOrder: 10,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 403,
            Label: "Light Mechanical",
            Name: "LightMechanical",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/LightMechanical.ashx",
            DisplayName: "Light Mechanical",
            SortOrder: 12,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 423,
            Label: "TirePass",
            Name: "TirePass",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/TirePass.ashx",
            DisplayName: "TirePass",
            SortOrder: 13,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
      ],
      FilteredCustomFields: [
        {
          CustomField: {
            Id: 347,
            Label: "Parking Spaces",
            Name: "ParkingSpaces",
            TypeName: "System.String",
            FacilitySubtypeId: 3,
            ValidationType: "Number",
            FacilityLogo: null,
            DisplayName: "Truck Parking",
            SortOrder: 0,
            IncludeInExcelExport: false,
            Section: null,
          },
          CustomFieldId: 347,
          FacilityId: 368,
          Value: "65",
        },
        {
          CustomField: {
            Id: 343,
            Label: "DEF # of Lanes",
            Name: "DEF#ofLanes",
            TypeName: "System.String",
            FacilitySubtypeId: 3,
            ValidationType: "Number",
            FacilityLogo: null,
            DisplayName: "DEF Lanes",
            SortOrder: 0,
            IncludeInExcelExport: false,
            Section: null,
          },
          CustomFieldId: 343,
          FacilityId: 368,
          Value: "8",
        },
      ],
      Site: {
        FuelPrices: [
          {
            SiteId: 368,
            ProductId: 1,
            ProductName: "UNL-REGULAR",
            FuelType: "Unleaded",
            LastPriceChangeDateTime: "07/21/2017 09:16:55",
            LastCheckInDateTime: "07/21/2017 09:25:51",
            CashPrice: 1.999,
            CreditPrice: null,
            DisplayName: "UNLEADED",
            DisplayOrder: "1",
            Group: 0,
            OrderInGroup: 1,
          },
          {
            SiteId: 368,
            ProductId: 8,
            ProductName: "UNL-PLUS B 66/34",
            FuelType: "Midgrade",
            LastPriceChangeDateTime: "07/21/2017 09:16:55",
            LastCheckInDateTime: "07/21/2017 09:25:51",
            CashPrice: 2.249,
            CreditPrice: null,
            DisplayName: "MIDGRADE",
            DisplayOrder: "2",
            Group: 0,
            OrderInGroup: 2,
          },
          {
            SiteId: 368,
            ProductId: 2,
            ProductName: "UNL-SUPER",
            FuelType: "Premium",
            LastPriceChangeDateTime: "07/21/2017 09:16:55",
            LastCheckInDateTime: "07/21/2017 09:25:51",
            CashPrice: 2.499,
            CreditPrice: null,
            DisplayName: "PREMIUM",
            DisplayOrder: "3",
            Group: 0,
            OrderInGroup: 3,
          },
          {
            SiteId: 368,
            ProductId: 3,
            ProductName: "DIESEL",
            FuelType: "Bio-Diesel B15",
            LastPriceChangeDateTime: "07/21/2017 09:16:55",
            LastCheckInDateTime: "07/21/2017 09:25:51",
            CashPrice: 2.429,
            CreditPrice: null,
            DisplayName: "DIESEL B15",
            DisplayOrder: "11",
            Group: 1,
            OrderInGroup: 1,
          },
          {
            SiteId: 368,
            ProductId: 5,
            ProductName: "DEF",
            FuelType: "Bulk DEF",
            LastPriceChangeDateTime: "07/21/2017 09:16:55",
            LastCheckInDateTime: "07/21/2017 09:25:51",
            CashPrice: 2.759,
            CreditPrice: null,
            DisplayName: "DEF",
            DisplayOrder: "12",
            Group: 1,
            OrderInGroup: 2,
          },
        ],
        Concepts: [
          {
            Concept: {
              Id: 4,
              IsActive: true,
              Name: "Arby's",
              ConceptIcon: "/-/media/Images/Amenities/Location-search/ArbysLogo.ashx",
              SortOrder: 1,
            },
            ConceptId: 4,
            IsLeased: false,
            SiteId: 368,
            FacilityStatusId: 4,
            LoyaltyTypeId: 1,
          },
        ],
        CustomFields: null,
        Acreage: 0,
        AreaRoadsideManagerId: "",
        DescriptiveAddress: "I-65, Exit 208",
        DistrictId: 17,
        EmployeeRelationsSpecialistId: "",
        EnvironmentalManagerId: "",
        ExitNumber: "208",
        Highway: "I-65",
        Latitude: 32.844151,
        Longitude: -86.591963,
        LossPreventionSpecialistId: "",
        OwnerLessorId: 2,
        RiskManagementRepresentativeId: "",
        SiteId: 368,
        SiteName: "Site 368",
        SiteNumber: 368,
        SitePreferredName: "Clanton",
        SiteRef: "d5399d36-4773-4056-add8-dcbc7485d40c",
        SiteStatusId: 1,
        SiteTypeId: 1,
        UTCOffset: -6,
      },
      AreaManagerId: null,
      AuditorId: null,
      ClosedDate: null,
      FacilityAreaId: null,
      FacilityId: 368,
      FacilityMaintenanceManagerId: null,
      FacilityManagerId: "000002991",
      FacilityRef: "6e8e532d-ebc1-e011-8b14-0050568d297a",
      FacilityStatusId: 4,
      FacilitySubTypeId: 3,
      FacilitySubtype: {
        Id: 3,
        Name: "Travel Stop",
      },
      MatureDate: "10/01/2008 00:00:00",
      Name: "FlyingK Travel Stop - 368",
      Number: 368,
      OpenDate: "09/20/2007 00:00:00",
      PreferredName: "Clanton",
      RecruiterId: "          ",
      SiteId: 368,
    },
    {
      AcceptedPaymentTypes: [
        {
          SiteManagementItem: {
            Title: "All Major Credit Cards",
            HideInSearch: false,
            SortOrder: 1,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Cash Accepted",
            HideInSearch: false,
            SortOrder: 2,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "ComCheck",
            HideInSearch: false,
            SortOrder: 3,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "EBT/SNAP Accepted",
            HideInSearch: false,
            SortOrder: 4,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Fleet One",
            HideInSearch: false,
            SortOrder: 5,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "EFS",
            HideInSearch: false,
            SortOrder: 6,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "FlyingK Express",
            HideInSearch: false,
            SortOrder: 7,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "MultiService",
            HideInSearch: false,
            SortOrder: 8,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "T-Chek",
            HideInSearch: false,
            SortOrder: 9,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "TCH",
            HideInSearch: false,
            SortOrder: 10,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "QuikQ FPS",
            HideInSearch: false,
            SortOrder: 11,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
      ],
      AdditionalAmenities: [
        {
          SiteManagementItem: {
            Title: "24-Hour Road Service",
            HideInSearch: false,
            SortOrder: 1,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Open 24-Hours",
            HideInSearch: false,
            SortOrder: 2,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Additives Available",
            HideInSearch: false,
            SortOrder: 3,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Calling Cards",
            HideInSearch: false,
            SortOrder: 4,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Check Cashing",
            HideInSearch: false,
            SortOrder: 5,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Copy & Fax Service",
            HideInSearch: false,
            SortOrder: 6,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "DEF Retail",
            HideInSearch: false,
            SortOrder: 7,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Overnight Parking",
            HideInSearch: false,
            SortOrder: 8,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Permit Fax",
            HideInSearch: false,
            SortOrder: 9,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "Loyalty Program",
            HideInSearch: false,
            SortOrder: 10,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
        {
          SiteManagementItem: {
            Title: "TripPak Express",
            HideInSearch: false,
            SortOrder: 11,
            IncludeInExcelExport: false,
            Section: "Amenities",
          },
        },
      ],
      Addresses: [
        {
          Address1: "16101 Hwy 84",
          Address2: "",
          AddressId: 842,
          AddressTypeId: 1,
          City: "Evergreen",
          Comments: "",
          County: null,
          Name: "Evergreen - 225",
          SpecialInstructions: "",
          State: "AL",
          Zip: "36401",
        },
      ],
      ContactMethods: [
        {
          Type: {
            Id: 1,
            Name: "Main Phone",
            IsActive: true,
          },
          Id: 1534,
          ContactMethodTypeId: 1,
          Data: "(251) 578-4496",
        },
        {
          Type: {
            Id: 5,
            Name: "Fax",
            IsActive: true,
          },
          Id: 1536,
          ContactMethodTypeId: 5,
          Data: "(251) 578-4831",
        },
        {
          Type: {
            Id: 2,
            Name: "Main Email",
            IsActive: true,
          },
          Id: 279,
          ContactMethodTypeId: 2,
          Data: "Store225@example.com",
        },
        {
          Type: {
            Id: 4,
            Name: "Rollover Phone",
            IsActive: true,
          },
          Id: 1535,
          ContactMethodTypeId: 4,
          Data: "(251) 578-4652",
        },
      ],
      CustomFields: [
        {
          CustomField: {
            Id: 411,
            Label: "Private Showers",
            Name: "PrivateShowers",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/shower.ashx",
            DisplayName: "Private Showers",
            SortOrder: 1,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 383,
            Label: "CAT Scales",
            Name: "CATScales",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/cat.ashx",
            DisplayName: "CAT Scales",
            SortOrder: 2,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 391,
            Label: "Wireless Internet",
            Name: "WirelessInternet",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/internet.ashx",
            DisplayName: "WiFi",
            SortOrder: 3,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 515,
            Label: "ATM",
            Name: "ATM",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/atm.ashx",
            DisplayName: "ATM",
            SortOrder: 4,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 13,
            Label: "Transflo",
            Name: "Transflo",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/transFlo.ashx",
            DisplayName: "Transflo",
            SortOrder: 5,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 371,
            Label: "Overnight Parking",
            Name: "OvernightParking",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/nightParking.ashx",
            DisplayName: "Truck Parking",
            SortOrder: 6,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 407,
            Label: "DEF Bulk Dispensers",
            Name: "DEFBulkDispensers",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/bulkDef.ashx",
            DisplayName: "Bulk DEF",
            SortOrder: 8,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 351,
            Label: "RF Service",
            Name: "RFService",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/rf.ashx",
            DisplayName: "RFID Pump Start",
            SortOrder: 9,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 387,
            Label: "National Tire Account",
            Name: "NationalTireAccount",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/tireCare.ashx",
            DisplayName: "Truck Tire Care",
            SortOrder: 10,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 535,
            Label: "Commercial Truck Oil Change",
            Name: "Commercial Truck Oil Cha",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/oil_icon_red_no_ring.ashx",
            DisplayName: "Commercial Truck Oil Change",
            SortOrder: 11,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 403,
            Label: "Light Mechanical",
            Name: "LightMechanical",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/LightMechanical.ashx",
            DisplayName: "Light Mechanical",
            SortOrder: 12,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 423,
            Label: "TirePass",
            Name: "TirePass",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/TirePass.ashx",
            DisplayName: "TirePass",
            SortOrder: 13,
            IncludeInExcelExport: true,
            Section: "Select Truck Services",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
        {
          CustomField: {
            Id: 419,
            Label: "Bulk Propane",
            Name: "BulkPropane",
            TypeName: "System.Boolean",
            FacilitySubtypeId: 3,
            ValidationType: "None",
            FacilityLogo: "/-/media/Images/Amenities/Location-search/propane.ashx",
            DisplayName: "Bulk Propane",
            SortOrder: 14,
            IncludeInExcelExport: true,
            Section: "Select Amenities",
          },
          CustomFieldId: 0,
          FacilityId: 0,
          Value: null,
        },
      ],
      FilteredCustomFields: [
        {
          CustomField: {
            Id: 347,
            Label: "Parking Spaces",
            Name: "ParkingSpaces",
            TypeName: "System.String",
            FacilitySubtypeId: 3,
            ValidationType: "Number",
            FacilityLogo: null,
            DisplayName: "Truck Parking",
            SortOrder: 0,
            IncludeInExcelExport: false,
            Section: null,
          },
          CustomFieldId: 347,
          FacilityId: 225,
          Value: "95",
        },
        {
          CustomField: {
            Id: 343,
            Label: "DEF # of Lanes",
            Name: "DEF#ofLanes",
            TypeName: "System.String",
            FacilitySubtypeId: 3,
            ValidationType: "Number",
            FacilityLogo: null,
            DisplayName: "DEF Lanes",
            SortOrder: 0,
            IncludeInExcelExport: false,
            Section: null,
          },
          CustomFieldId: 343,
          FacilityId: 225,
          Value: "8",
        },
      ],
      Site: {
        FuelPrices: [
          {
            SiteId: 225,
            ProductId: 1,
            ProductName: "UNL-REGULAR",
            FuelType: "Unleaded",
            LastPriceChangeDateTime: "07/21/2017 09:10:39",
            LastCheckInDateTime: "07/21/2017 09:23:02",
            CashPrice: 2.059,
            CreditPrice: null,
            DisplayName: "UNLEADED",
            DisplayOrder: "1",
            Group: 0,
            OrderInGroup: 1,
          },
          {
            SiteId: 225,
            ProductId: 8,
            ProductName: "UNL-PLUS B 66/34",
            FuelType: "Midgrade",
            LastPriceChangeDateTime: "07/21/2017 09:10:39",
            LastCheckInDateTime: "07/21/2017 09:23:02",
            CashPrice: 2.309,
            CreditPrice: null,
            DisplayName: "MIDGRADE",
            DisplayOrder: "2",
            Group: 0,
            OrderInGroup: 2,
          },
          {
            SiteId: 225,
            ProductId: 2,
            ProductName: "UNL-SUPER",
            FuelType: "Premium",
            LastPriceChangeDateTime: "07/21/2017 09:10:39",
            LastCheckInDateTime: "07/21/2017 09:23:02",
            CashPrice: 2.559,
            CreditPrice: null,
            DisplayName: "PREMIUM",
            DisplayOrder: "3",
            Group: 0,
            OrderInGroup: 3,
          },
          {
            SiteId: 225,
            ProductId: 3,
            ProductName: "DIESEL",
            FuelType: "Bio-Diesel B15",
            LastPriceChangeDateTime: "07/21/2017 09:10:39",
            LastCheckInDateTime: "07/21/2017 09:23:02",
            CashPrice: 2.429,
            CreditPrice: 2.479,
            DisplayName: "DIESEL B15",
            DisplayOrder: "11",
            Group: 1,
            OrderInGroup: 1,
          },
          {
            SiteId: 225,
            ProductId: 5,
            ProductName: "DEF",
            FuelType: "Bulk DEF",
            LastPriceChangeDateTime: "07/21/2017 09:10:39",
            LastCheckInDateTime: "07/21/2017 09:23:02",
            CashPrice: 2.759,
            CreditPrice: null,
            DisplayName: "DEF",
            DisplayOrder: "12",
            Group: 1,
            OrderInGroup: 2,
          },
        ],
        Concepts: [
          {
            Concept: {
              Id: 4,
              IsActive: true,
              Name: "Arby's",
              ConceptIcon: "/-/media/Images/Amenities/Location-search/ArbysLogo.ashx",
              SortOrder: 1,
            },
            ConceptId: 4,
            IsLeased: false,
            SiteId: 225,
            FacilityStatusId: 4,
            LoyaltyTypeId: 1,
          },
        ],
        CustomFields: null,
        Acreage: 0,
        AreaRoadsideManagerId: "",
        DescriptiveAddress: "I-65, Exit 93",
        DistrictId: 17,
        EmployeeRelationsSpecialistId: "",
        EnvironmentalManagerId: "",
        ExitNumber: "93",
        Highway: "I-65",
        Latitude: 31.419105,
        Longitude: -87.00765,
        LossPreventionSpecialistId: "",
        OwnerLessorId: 2,
        RiskManagementRepresentativeId: "",
        SiteId: 225,
        SiteName: "Site 225",
        SiteNumber: 225,
        SitePreferredName: "Evergreen",
        SiteRef: "47b67119-8445-4b8a-95d2-d0ded442a05e",
        SiteStatusId: 1,
        SiteTypeId: 1,
        UTCOffset: -6,
      },
      AreaManagerId: null,
      AuditorId: "000001523",
      ClosedDate: null,
      FacilityAreaId: null,
      FacilityId: 225,
      FacilityMaintenanceManagerId: null,
      FacilityManagerId: "000162956",
      FacilityRef: "5c8d532d-ebc1-e011-8b14-0050568d297a",
      FacilityStatusId: 4,
      FacilitySubTypeId: 3,
      FacilitySubtype: {
        Id: 3,
        Name: "Travel Stop",
      },
      MatureDate: "07/01/2011 00:00:00",
      Name: "FlyingK Travel Stop - 225",
      Number: 225,
      OpenDate: "06/17/2010 00:00:00",
      PreferredName: "Evergreen",
      RecruiterId: "          ",
      SiteId: 225,
    },
  ];
  return Promise.resolve(db);
}
